

coauth-name: coauth-name.tex;
	pdflatex -shell-escape coauth-name.tex
coauth-name-h: coauth-name-h.tex;
	pdflatex -shell-escape coauth-name-h.tex
coauth-name-sh: coauth-name-sh.tex;
	pdflatex -shell-escape coauth-name-sh.tex

graphs: coauth-name coauth-name-h coauth-name-sh;
